// <auto-generated />
using System;
using DrinkStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrinkStore.Migrations
{
    [DbContext(typeof(DrinkStoreContext))]
    [Migration("20260718005956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrinkStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại nước ngọt có ga, sảng khoái và đã khát",
                            Name = "Nước ngọt"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trà xanh, trà đóng chai thanh mát, giải độc",
                            Name = "Trà"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cà phê đóng lon, pha sẵn thơm ngon, tỉnh táo tức thì",
                            Name = "Cà phê"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nước ép trái cây tự nhiên, giàu vitamin",
                            Name = "Nước ép"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nước tinh khiết và nước khoáng bổ sung vi chất",
                            Name = "Nước khoáng"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sữa tươi, sữa tiệt trùng thơm béo, bổ dưỡng",
                            Name = "Sữa"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bổ sung năng lượng mạnh mẽ cho ngày dài hoạt động",
                            Name = "Nước tăng lực"
                        });
                });

            modelBuilder.Entity("DrinkStore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hệ thống DrinkStore",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@drinkstore.com",
                            FullName = "Quản trị viên",
                            Password = "admin123",
                            Phone = "0123456789",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DrinkStore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalMoney")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DrinkStore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DrinkStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Coca-Cola",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước ngọt có ga Coca-Cola hương vị độc đáo nguyên bản, giúp đập tan cơn khát, mang lại cảm giác sảng khoái tức thì cùng bữa ăn ngon.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/2/27/Coca_Cola_Flasche_-_Original_Taste.jpg",
                            IsFeatured = true,
                            IsNew = false,
                            Price = 10000m,
                            ProductName = "Coca-Cola Original vị nguyên bản",
                            Quantity = 120,
                            Status = true,
                            Volume = "330ml"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Pepsi",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước ngọt Pepsi vị chanh không calo cực kỳ thích hợp cho người ăn kiêng, giải khát sảng khoái mà không lo tăng cân.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/d/dd/Pepsi_Can.jpg",
                            IsFeatured = true,
                            IsNew = true,
                            Price = 10000m,
                            ProductName = "Pepsi vị chanh không calo",
                            Quantity = 150,
                            Status = true,
                            Volume = "330ml"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Sprite",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước giải khát có ga hương chanh tự nhiên, mang lại cảm giác sảng khoái tột đỉnh cho người thưởng thức.",
                            Image = "https://images.unsplash.com/photo-1625772291427-39f64aa5eea7?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 9500m,
                            ProductName = "Nước ngọt Sprite vị chanh",
                            Quantity = 80,
                            Status = true,
                            Volume = "330ml"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Fanta",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước ngọt Fanta hương cam thơm mát bùng nổ, có ga cực kỳ sảng khoái, kích thích vị giác.",
                            Image = "https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 9500m,
                            ProductName = "Fanta hương Cam",
                            Quantity = 90,
                            Status = true,
                            Volume = "330ml"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Sting",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sting dâu tây đỏ bùng nổ năng lượng, nhân sâm thơm ngon kích thích tỉnh táo sảng khoái tức thì.",
                            Image = "https://cdnv2.tgdd.vn/bhx-static/bhx/Products/Images/3226/76520/bhx/nuoc-tang-luc-sting-dau-pet-330ml_202509291516185862.jpg",
                            IsFeatured = true,
                            IsNew = true,
                            Price = 12000m,
                            ProductName = "Nước tăng lực Sting hương Dâu đỏ",
                            Quantity = 200,
                            Status = true,
                            Volume = "330ml"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Red Bull",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước tăng lực bò húc Red Bull nhập khẩu Thái Lan giúp tỉnh táo tinh thần, bổ sung năng lượng dồi dào.",
                            Image = "https://images.unsplash.com/photo-1613946069412-38f7f1ff0b65?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = true,
                            IsNew = false,
                            Price = 15000m,
                            ProductName = "Nước tăng lực Red Bull Thái Lan",
                            Quantity = 350,
                            Status = true,
                            Volume = "250ml"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Number One",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước uống năng lượng Number One đóng chai tiện dụng giúp bạn vượt qua mệt mỏi, chinh phục mọi thử thách.",
                            Image = "https://images.unsplash.com/photo-1543257580-7269da773bf5?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 10000m,
                            ProductName = "Nước tăng lực Number One chai",
                            Quantity = 110,
                            Status = true,
                            Volume = "250ml"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Revive",
                            CategoryId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Revive chanh muối bù nước bù khoáng tức thì cho người hoạt động thể thao, đổ mồ hôi nhiều.",
                            Image = "https://images.unsplash.com/photo-1527960656306-b3a951473295?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = true,
                            IsNew = false,
                            Price = 11000m,
                            ProductName = "Nước bù khoáng Revive Chanh Muối",
                            Quantity = 140,
                            Status = true,
                            Volume = "390ml"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Aquafina",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước uống tinh khiết Aquafina qua hệ thống lọc 7 bước chuẩn Hoa Kỳ mang lại nguồn nước thanh khiết tuyệt đối.",
                            Image = "https://aquafinawater.vn/library/module_new/san-pham-cua-aquafina_s5874.jpg",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 6000m,
                            ProductName = "Nước tinh khiết Aquafina",
                            Quantity = 500,
                            Status = true,
                            Volume = "500ml"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "La Vie",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "La Vie chứa nhiều khoáng chất tự nhiên quý giá tốt cho sức khỏe, thích hợp uống mỗi ngày.",
                            Image = "https://images.unsplash.com/photo-1560011536-1855e82a0ecf?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 6500m,
                            ProductName = "Nước khoáng thiên nhiên La Vie",
                            Quantity = 400,
                            Status = true,
                            Volume = "500ml"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Dasani",
                            CategoryId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước đóng chai Dasani tinh khiết chất lượng cao của hãng Coca-Cola Việt Nam, an toàn cho cả gia đình.",
                            Image = "https://dasaniwater.vn/library/module_new/cac-thac-mac-khach-hang-tieu-dung_s3464.jpg",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 6000m,
                            ProductName = "Nước tinh khiết Dasani",
                            Quantity = 300,
                            Status = true,
                            Volume = "500ml"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "THP",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Được làm từ lá trà xanh tươi ngon vùng Thái Nguyên kết hợp với hương chanh tự nhiên, chứa EGCG chống oxy hóa mạnh mẽ.",
                            Image = "https://cdnv2.tgdd.vn/bhx-static/bhx/Products/Images/8938/85739/bhx/fgjiol_202410140914265805.jpg",
                            IsFeatured = true,
                            IsNew = true,
                            Price = 10000m,
                            ProductName = "Trà Xanh Không Độ hương Chanh",
                            Quantity = 250,
                            Status = true,
                            Volume = "455ml"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "C2",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trà xanh đóng chai C2 thơm mát hương đào kết hợp chanh chua nhẹ, thanh lọc cơ thể cực kỳ hiệu quả.",
                            Image = "https://cdn.hstatic.net/products/200001149339/c2_chanh_953ef6250c37477db3a55e21e051b037_1024x1024.jpg",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 9000m,
                            ProductName = "Trà đào C2 hương chanh",
                            Quantity = 180,
                            Status = true,
                            Volume = "360ml"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Wonderfarm",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wonderfarm trà bí đao thanh ngọt tự nhiên, giải độc mát gan, là thức uống truyền thống tuyệt hảo.",
                            Image = "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 8500m,
                            ProductName = "Trà Bí Đao Wonderfarm lon",
                            Quantity = 160,
                            Status = true,
                            Volume = "310ml"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Lipton",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lipton trà chanh lon mát lạnh, thơm mùi trà đen và chua chua vị chanh, uống cùng đá cực ngon.",
                            Image = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = true,
                            IsNew = false,
                            Price = 11000m,
                            ProductName = "Lipton Ice Tea vị Chanh hộp pha sẵn",
                            Quantity = 130,
                            Status = true,
                            Volume = "330ml"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Nestlé",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nestlé Milo bổ sung canxi và năng lượng hoạt chất Active-Go từ mầm lúa mạch, giúp trẻ em luôn năng động khỏe mạnh.",
                            Image = "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = true,
                            IsNew = true,
                            Price = 14000m,
                            ProductName = "Sữa lúa mạch Nestlé Milo lon",
                            Quantity = 210,
                            Status = true,
                            Volume = "180ml"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "TH True Milk",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sữa tươi sạch TH True Milk ít đường được làm hoàn toàn từ sữa tươi sạch nguyên chất của trang trại TH.",
                            Image = "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=60",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 9000m,
                            ProductName = "Sữa tươi tiệt trùng TH True Milk ít đường",
                            Quantity = 300,
                            Status = true,
                            Volume = "180ml"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Vinamilk",
                            CategoryId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sữa tươi tiệt trùng Vinamilk thơm ngon béo ngậy, giàu vitamin A, D3 và canxi giúp sáng mắt khỏe xương.",
                            Image = "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/9/8934673500357-2.jpg.webp",
                            IsFeatured = false,
                            IsNew = false,
                            Price = 8500m,
                            ProductName = "Sữa dinh dưỡng Vinamilk có đường",
                            Quantity = 280,
                            Status = true,
                            Volume = "180ml"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Nescafé",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cà phê sữa đá Nescafé mang lại hương vị cà phê phin đậm đà kết hợp sữa béo ngậy chuẩn gu Việt.",
                            Image = "https://cdn.tgdd.vn/Products/Images/8966/195217/bhx/ca-phe-sua-nescafe-170ml-201904171555454406.jpg",
                            IsFeatured = true,
                            IsNew = false,
                            Price = 15000m,
                            ProductName = "Nescafé sữa đá đóng lon",
                            Quantity = 170,
                            Status = true,
                            Volume = "180ml"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Highlands Coffee",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hương vị cà phê sữa đá trứ danh của Highlands Coffee nay được đóng lon tiện lợi, đậm đà tỉnh táo.",
                            Image = "https://www.highlandscoffee.com.vn/vnt_upload/product/06_2023/HLC_New_logo_5.1_Products__NEW_CAN_CFS_INTERNATIONAL_185ml.jpg",
                            IsFeatured = true,
                            IsNew = true,
                            Price = 19000m,
                            ProductName = "Highlands Coffee Cà Phê Sữa Đá lon",
                            Quantity = 220,
                            Status = true,
                            Volume = "235ml"
                        });
                });

            modelBuilder.Entity("DrinkStore.Models.Order", b =>
                {
                    b.HasOne("DrinkStore.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DrinkStore.Models.OrderDetail", b =>
                {
                    b.HasOne("DrinkStore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrinkStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DrinkStore.Models.Product", b =>
                {
                    b.HasOne("DrinkStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DrinkStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DrinkStore.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DrinkStore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
